dist: xenial
language: python
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit

notifications:
  irc: "chat.freenode.net#pil"

# Run fast lint first to get fast feedback.
# Run slower CPUs next, to give them a headstart and reduce waiting time.
# Then run the remainder.

matrix:
  fast_finish: true
  include:
    - python: "3.9-dev"
      name: "3.9-dev Xenial"
      services: xvfb

install:
  - |
    if [ "$LINT" == "true" ]; then
      pip install tox
    else
      .ci/install.sh;
    fi

script:
- |
  if [ "$LINT" == "true" ]; then
    tox -e lint
  else
    .ci/build.sh
    .ci/test.sh
  fi

after_success:
- |
  if [ "$LINT" == "" ]; then
    .ci/after_success.sh
  fi
