name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_CORE: sysmon
  FORCE_COLOR: 1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: "macos-14"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install macOS dependencies
      run: |
        brew update
        brew install python@3.12 pillow freetype fribidi harfbuzz libpng libraqm
        brew list --versions

    - name: Test
      run: |
        python3 demo.py
